services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: taxidermy-website-backend-prod
    volumes:
      - /etc/ssl:/etc/ssl
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: on-failure